-- PRODUCT ANALYSIS 

-- WHICH THEMES HAVE THE MOST LEGO SETS?
SELECT
THEME,
COUNT(*) AS TOTAL_SETS
FROM lego_sets
GROUP BY theme
ORDER BY TOTAL_SETS DESC
LIMIT 10;

-- WHICH THEMES HAVE THE MOST TOTAL PIECES?
SELECT 
THEME,
SUM(PIECES) AS TOTAL_PIECES
FROM lego_sets
WHERE PIECES IS NOT NULL
GROUP BY theme
ORDER BY TOTAL_PIECES DESC
LIMIT 10;
-- START WARS THEME HAS MOST NUMBER OF TOTAL PIECES FOLLOWED BY  TECHNIC ON NUMBER TWO.

-- WHICH SET CONTAINS THE MOST PIECES?
SELECT
NAME, 
THEME,
PIECES
FROM lego_sets
WHERE PIECES IS NOT NULL
ORDER BY PIECES DESC
LIMIT 20;
-- SUPER PACK 5 IN 1 LEGO SET HAD HIGHEST NUMBER OF PIECES

-- WHICH SET HAS THE MOST NUMBER OF MINIFIGS?
SELECT 
NAME,
THEME,
MINIFIGS
FROM LEGO_SETS
WHERE MINIFIGS IS NOT NULL
ORDER BY MINIFIGS DESC
LIMIT 10;

-- WHAT IS THE RELATIONSHIP BETWEEN PIECES AND PRICES?
SELECT
    theme,
    ROUND(AVG(pieces), 2) AS avg_pieces,
    ROUND(AVG(US_retailPrice), 2) AS avg_price
FROM lego_sets
WHERE pieces IS NOT NULL
  AND US_retailPrice IS NOT NULL
GROUP BY theme
HAVING COUNT(*) >= 5
ORDER BY avg_price DESC;

